/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface NfcPosPaymentHubInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOwnership"
      | "configureMerchant"
      | "feeRecipient"
      | "merchants"
      | "owner"
      | "payErc20"
      | "payNative"
      | "pendingOwner"
      | "platformFeeBps"
      | "renounceOwnership"
      | "setPlatformFee"
      | "settledInvoiceIds"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MerchantConfigured"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "PaymentRecorded"
      | "PlatformFeeUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "configureMerchant",
    values: [AddressLike, boolean, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "merchants",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payErc20",
    values: [BytesLike, AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "payNative",
    values: [BytesLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settledInvoiceIds",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "configureMerchant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "merchants", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payErc20", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payNative", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settledInvoiceIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace MerchantConfiguredEvent {
  export type InputTuple = [
    merchant: AddressLike,
    active: boolean,
    payout: AddressLike,
    metadataURI: string
  ];
  export type OutputTuple = [
    merchant: string,
    active: boolean,
    payout: string,
    metadataURI: string
  ];
  export interface OutputObject {
    merchant: string;
    active: boolean;
    payout: string;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentRecordedEvent {
  export type InputTuple = [
    invoiceId: BytesLike,
    merchant: AddressLike,
    payer: AddressLike,
    token: AddressLike,
    grossAmount: BigNumberish,
    feeAmount: BigNumberish,
    payerUserHash: BytesLike
  ];
  export type OutputTuple = [
    invoiceId: string,
    merchant: string,
    payer: string,
    token: string,
    grossAmount: bigint,
    feeAmount: bigint,
    payerUserHash: string
  ];
  export interface OutputObject {
    invoiceId: string;
    merchant: string;
    payer: string;
    token: string;
    grossAmount: bigint;
    feeAmount: bigint;
    payerUserHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeUpdatedEvent {
  export type InputTuple = [feeBps: BigNumberish, feeRecipient: AddressLike];
  export type OutputTuple = [feeBps: bigint, feeRecipient: string];
  export interface OutputObject {
    feeBps: bigint;
    feeRecipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NfcPosPaymentHub extends BaseContract {
  connect(runner?: ContractRunner | null): NfcPosPaymentHub;
  waitForDeployment(): Promise<this>;

  interface: NfcPosPaymentHubInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  configureMerchant: TypedContractMethod<
    [
      merchant: AddressLike,
      active: boolean,
      payout: AddressLike,
      metadataURI: string
    ],
    [void],
    "nonpayable"
  >;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  merchants: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, string, string] & {
        active: boolean;
        payout: string;
        metadataURI: string;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  payErc20: TypedContractMethod<
    [
      invoiceId: BytesLike,
      merchant: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      payerUserHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  payNative: TypedContractMethod<
    [invoiceId: BytesLike, merchant: AddressLike, payerUserHash: BytesLike],
    [void],
    "payable"
  >;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setPlatformFee: TypedContractMethod<
    [nextFeeBps: BigNumberish, nextFeeRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  settledInvoiceIds: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "configureMerchant"
  ): TypedContractMethod<
    [
      merchant: AddressLike,
      active: boolean,
      payout: AddressLike,
      metadataURI: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "merchants"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, string, string] & {
        active: boolean;
        payout: string;
        metadataURI: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payErc20"
  ): TypedContractMethod<
    [
      invoiceId: BytesLike,
      merchant: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      payerUserHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "payNative"
  ): TypedContractMethod<
    [invoiceId: BytesLike, merchant: AddressLike, payerUserHash: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<
    [nextFeeBps: BigNumberish, nextFeeRecipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settledInvoiceIds"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "MerchantConfigured"
  ): TypedContractEvent<
    MerchantConfiguredEvent.InputTuple,
    MerchantConfiguredEvent.OutputTuple,
    MerchantConfiguredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentRecorded"
  ): TypedContractEvent<
    PaymentRecordedEvent.InputTuple,
    PaymentRecordedEvent.OutputTuple,
    PaymentRecordedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeUpdated"
  ): TypedContractEvent<
    PlatformFeeUpdatedEvent.InputTuple,
    PlatformFeeUpdatedEvent.OutputTuple,
    PlatformFeeUpdatedEvent.OutputObject
  >;

  filters: {
    "MerchantConfigured(address,bool,address,string)": TypedContractEvent<
      MerchantConfiguredEvent.InputTuple,
      MerchantConfiguredEvent.OutputTuple,
      MerchantConfiguredEvent.OutputObject
    >;
    MerchantConfigured: TypedContractEvent<
      MerchantConfiguredEvent.InputTuple,
      MerchantConfiguredEvent.OutputTuple,
      MerchantConfiguredEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentRecorded(bytes32,address,address,address,uint256,uint256,bytes32)": TypedContractEvent<
      PaymentRecordedEvent.InputTuple,
      PaymentRecordedEvent.OutputTuple,
      PaymentRecordedEvent.OutputObject
    >;
    PaymentRecorded: TypedContractEvent<
      PaymentRecordedEvent.InputTuple,
      PaymentRecordedEvent.OutputTuple,
      PaymentRecordedEvent.OutputObject
    >;

    "PlatformFeeUpdated(uint16,address)": TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
    PlatformFeeUpdated: TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
  };
}
